logging:
  level: debug

server:
  error:
    include-stacktrace: always

api:
  scope: user:email
  authorize_uri: https://github.com/login/oauth/authorize
  access_token_url: https://github.com/login/oauth/access_token
  emails_url: https://api.github.com/user/emails
#  client_id: 4a720c2e230741984499
#  client_secret: 0bb36c527f43de952b01551ebf490b296d4c6831
#  redirect_uri: http://192.168.1.103:8080/authorized